"""Controlled, authoritative source metadata for the curated corpus.

URLs in this registry are application-owned metadata.  They are never supplied
to, generated by, or inferred from the language model.
"""

import json
from pathlib import Path

TRUSTED_SOURCES = {
    "Patents Act, 1970": {
        "domain": "patent",
        "source_organization": "IP India",
        "authority": "IP India",
        "jurisdiction": "India",
        "official_listing_url": "https://ipindia.gov.in/acts/patent-act-1970",
        "official_pdf_url": None,
    },
    "Patents Rules, 2003": {
        "domain": "patent",
        "source_organization": "IP India",
        "authority": "IP India",
        "jurisdiction": "India",
        "official_listing_url": "https://ipindia.gov.in/resource/patents-resources-rules",
        "official_pdf_url": None,
    },
    "Guidelines for Examination of Ayush Related Inventions, 2025": {
        "domain": "patent",
        "source_organization": "IP India",
        "authority": "IP India",
        "jurisdiction": "India",
        "document_version": "2025 edition",
        "document_status": "Official examination guidance",
        "official_listing_url": "https://www.ipindia.gov.in/resource/patents-resources-guidelines",
        "official_pdf_url": "https://www.ipindia.gov.in/frontend/pdf/patents/guidelines/Guidelines%20for%20Examination%20of%20Ayush%20Related%20Inventions.pdf",
    },
    "Biological Diversity Act, 2002 (as amended in 2023)": {
        "domain": "abs",
        "source_organization": "Kerala State Biodiversity Board",
        "authority": "Kerala State Biodiversity Board",
        "jurisdiction": "India",
        "document_version": "As amended by the Biological Diversity (Amendment) Act, 2023",
        "document_status": "Consolidated text; amendment provisions commenced as notified",
        "official_listing_url": None,
        "official_pdf_url": "https://keralabiodiversity.org/wp-content/uploads/2025/07/BD-Act-2002-2023-1.pdf",
    },
    "Biological Diversity Rules, 2024": {
        "domain": "abs",
        "source_organization": "Ministry of Environment, Forest and Climate Change",
        "authority": "Government of India Gazette",
        "jurisdiction": "India",
        "document_version": "G.S.R. 665(E), 22 October 2024",
        "document_status": "In force; read with the 2025 Amendment Rules",
        "official_listing_url": None,
        "official_pdf_url": "https://egazette.gov.in/WriteReadData/2024/258244.pdf",
    },
    "Biological Diversity (Amendment) Rules, 2025": {
        "domain": "abs",
        "source_organization": "Ministry of Environment, Forest and Climate Change",
        "authority": "Government of India Gazette",
        "jurisdiction": "India",
        "document_version": "G.S.R. 295(E), 6 May 2025; effective 1 November 2025",
        "document_status": "Current amendment to the Biological Diversity Rules, 2024",
        "official_listing_url": None,
        "official_pdf_url": "https://egazette.gov.in/WriteReadData/2025/262974.pdf",
    },
    "Biological Diversity (ABS) Regulations, 2025": {
        "domain": "abs",
        "source_organization": "National Biodiversity Authority",
        "authority": "National Biodiversity Authority",
        "jurisdiction": "India",
        "document_version": "Notified 29 April 2025; Gazette No. 332, published 30 April 2025",
        "document_status": "Current; supersedes the 2014 ABS Regulations",
        "official_listing_url": None,
        "official_pdf_url": "https://www.nbaindia.nic.in/sites/default/files/2026-07/GNABSREG_2025.pdf",
    },
    "WIPO GRATK Treaty, 2024": {
        "domain": "tkdl_prior_art",
        "source_organization": "World Intellectual Property Organization",
        "authority": "World Intellectual Property Organization",
        "jurisdiction": "International",
        "document_version": "Adopted 24 May 2024",
        "document_status": "Not yet in force as of 24 September 2026, per WIPO treaty status",
        "official_listing_url": None,
        "official_pdf_url": "https://www.wipo.int/treaties/en/docs/pdf/gratk.pdf",
    },
}


def trusted_source_for(document):
    """Return registry metadata plus generated International source metadata."""
    source = dict(TRUSTED_SOURCES.get(document, {}))
    manifest = Path(__file__).resolve().parent.parent / "data" / "international_sources.json"
    if manifest.exists():
        try:
            records = json.loads(manifest.read_text(encoding="utf-8"))
            record = next((item for item in records if item.get("document") == document), {})
            for key, value in record.items():
                if value is None or value == "TODO":
                    source.setdefault(key, value)
                else:
                    source[key] = value
        except (OSError, json.JSONDecodeError):
            pass
    return source
